// <auto-generated />
using System;
using CVGS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVGS.Migrations
{
    [DbContext(typeof(CvgsDbContext))]
    [Migration("20241122194804_AddOrdersAndOrderDetailsGameType")]
    partial class AddOrdersAndOrderDetailsGameType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AptSuite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("SameAsShippingAddress")
                        .HasColumnType("bit");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CVGS.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CVGS.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("GameId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CVGS.Entities.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("DownloadSize")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageSupport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            Category = "Sandbox",
                            CoverImageURL = "/images/minecraft.jpg",
                            Description = "A sandbox game with endless possibilities.",
                            DownloadSize = 1500000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "PC",
                            Price = 26.95m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            GameID = 2,
                            Category = "RPG",
                            CoverImageURL = "/images/witcher3.jpg",
                            Description = "An open-world RPG with a gripping story.",
                            DownloadSize = 3500000000L,
                            LanguageSupport = "English, French",
                            Platform = "PC",
                            Price = 39.99m,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            GameID = 3,
                            Category = "RPG",
                            CoverImageURL = "/images/cyberpunk2077.jpg",
                            Description = "A futuristic RPG with a vast city to explore.",
                            DownloadSize = 5000000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "PC",
                            Price = 59.99m,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            GameID = 4,
                            Category = "Shooter",
                            CoverImageURL = "/images/halflife_alyx.jpg",
                            Description = "A VR game set in the Half-Life universe.",
                            DownloadSize = 2000000000L,
                            LanguageSupport = "English, Russian",
                            Platform = "PC",
                            Price = 59.99m,
                            Title = "Half-Life: Alyx"
                        },
                        new
                        {
                            GameID = 5,
                            Category = "Action",
                            CoverImageURL = "/images/gtav.jpg",
                            Description = "A sandbox game with open-world action.",
                            DownloadSize = 6500000000L,
                            LanguageSupport = "English, French",
                            Platform = "PC",
                            Price = 29.99m,
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            GameID = 6,
                            Category = "Shooter",
                            CoverImageURL = "/images/halo_infinite.jpg",
                            Description = "A first-person shooter set in a sci-fi universe.",
                            DownloadSize = 6000000000L,
                            LanguageSupport = "English, French",
                            Platform = "Xbox Series S/X",
                            Price = 59.99m,
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            GameID = 7,
                            Category = "Racing",
                            CoverImageURL = "/images/forza_horizon5.jpg",
                            Description = "A racing game with beautiful open-world environments.",
                            DownloadSize = 8000000000L,
                            LanguageSupport = "English, Italian",
                            Platform = "Xbox Series S/X",
                            Price = 49.99m,
                            Title = "Forza Horizon 5"
                        },
                        new
                        {
                            GameID = 8,
                            Category = "Sports",
                            CoverImageURL = "/images/fifa_23.jpg",
                            Description = "The latest installment in the FIFA soccer series.",
                            DownloadSize = 2500000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "Xbox Series S/X",
                            Price = 59.99m,
                            Title = "FIFA 23"
                        },
                        new
                        {
                            GameID = 9,
                            Category = "RPG",
                            CoverImageURL = "/images/the_ascent.jpg",
                            Description = "A cyberpunk RPG set in a dystopian world.",
                            DownloadSize = 5000000000L,
                            LanguageSupport = "English, Japanese",
                            Platform = "Xbox Series S/X",
                            Price = 39.99m,
                            Title = "The Ascent"
                        },
                        new
                        {
                            GameID = 10,
                            Category = "Platformer",
                            CoverImageURL = "/images/psychonauts2.jpg",
                            Description = "A quirky platformer with mind-bending puzzles.",
                            DownloadSize = 4500000000L,
                            LanguageSupport = "English, French",
                            Platform = "Xbox Series S/X",
                            Price = 59.99m,
                            Title = "Psychonauts 2"
                        },
                        new
                        {
                            GameID = 11,
                            Category = "Sports",
                            CoverImageURL = "/images/fifa_23.jpg",
                            Description = "The latest installment in the FIFA soccer series.",
                            DownloadSize = 2500000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "Xbox One",
                            Price = 59.99m,
                            Title = "FIFA 23"
                        },
                        new
                        {
                            GameID = 12,
                            Category = "RPG",
                            CoverImageURL = "/images/skyrim.jpg",
                            Description = "A fantasy RPG with an open-world to explore.",
                            DownloadSize = 1200000000L,
                            LanguageSupport = "English, German",
                            Platform = "Xbox One",
                            Price = 39.99m,
                            Title = "The Elder Scrolls V: Skyrim"
                        },
                        new
                        {
                            GameID = 13,
                            Category = "Sandbox",
                            CoverImageURL = "/images/minecraft.jpg",
                            Description = "A sandbox game with endless possibilities.",
                            DownloadSize = 1500000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "Xbox One",
                            Price = 26.95m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            GameID = 14,
                            Category = "Shooter",
                            CoverImageURL = "/images/cod_mw.jpg",
                            Description = "A first-person shooter with intense multiplayer.",
                            DownloadSize = 6000000000L,
                            LanguageSupport = "English, Russian",
                            Platform = "Xbox One",
                            Price = 59.99m,
                            Title = "Call of Duty: Modern Warfare III"
                        },
                        new
                        {
                            GameID = 15,
                            Category = "Racing",
                            CoverImageURL = "/images/forza_horizon4.jpg",
                            Description = "A racing game with beautiful open-world environments.",
                            DownloadSize = 6000000000L,
                            LanguageSupport = "English, Italian",
                            Platform = "Xbox One",
                            Price = 49.99m,
                            Title = "Forza Horizon 4"
                        },
                        new
                        {
                            GameID = 16,
                            Category = "Action",
                            CoverImageURL = "/images/spider_man_miles_morales.jpg",
                            Description = "A superhero game with incredible web-slinging mechanics.",
                            DownloadSize = 500000000L,
                            LanguageSupport = "English, German",
                            Platform = "PlayStation 5",
                            Price = 59.99m,
                            Title = "Spider-Man: Miles Morales"
                        },
                        new
                        {
                            GameID = 17,
                            Category = "Action/RPG",
                            CoverImageURL = "/images/demons_souls.jpg",
                            Description = "A remake of the classic action RPG with amazing visuals.",
                            DownloadSize = 1000000000L,
                            LanguageSupport = "English, Russian",
                            Platform = "PlayStation 5",
                            Price = 59.99m,
                            Title = "Demon's Souls"
                        },
                        new
                        {
                            GameID = 18,
                            Category = "RPG",
                            CoverImageURL = "/images/final_fantasy_xvi.jpg",
                            Description = "A high fantasy RPG with intense combat.",
                            DownloadSize = 1500000000L,
                            LanguageSupport = "English, Japanese",
                            Platform = "PlayStation 5",
                            Price = 69.99m,
                            Title = "Final Fantasy XVI"
                        },
                        new
                        {
                            GameID = 19,
                            Category = "Action",
                            CoverImageURL = "/images/ratchet_and_clank.jpg",
                            Description = "A visually stunning action-adventure platformer.",
                            DownloadSize = 4500000000L,
                            LanguageSupport = "English, French",
                            Platform = "PlayStation 5",
                            Price = 69.99m,
                            Title = "Ratchet & Clank: Rift Apart"
                        },
                        new
                        {
                            GameID = 20,
                            Category = "Shooter",
                            CoverImageURL = "/images/returnal.jpg",
                            Description = "A roguelike third-person shooter with sci-fi elements.",
                            DownloadSize = 1500000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "PlayStation 5",
                            Price = 59.99m,
                            Title = "Returnal"
                        },
                        new
                        {
                            GameID = 21,
                            Category = "Action/Adventure",
                            CoverImageURL = "/images/uncharted_4.jpg",
                            Description = "A treasure-hunting adventure with stunning visuals.",
                            DownloadSize = 500000000L,
                            LanguageSupport = "English, French",
                            Platform = "PlayStation 4",
                            Price = 39.99m,
                            Title = "Uncharted 4: A Thief's End"
                        },
                        new
                        {
                            GameID = 22,
                            Category = "Action/Adventure",
                            CoverImageURL = "/images/last_of_us2.jpg",
                            Description = "A gripping action adventure with deep storytelling.",
                            DownloadSize = 5000000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "PlayStation 4",
                            Price = 59.99m,
                            Title = "The Last of Us Part II"
                        },
                        new
                        {
                            GameID = 23,
                            Category = "Action",
                            CoverImageURL = "/images/ghost_of_tsushima.jpg",
                            Description = "An open-world action game set in feudal Japan.",
                            DownloadSize = 4500000000L,
                            LanguageSupport = "English, Russian",
                            Platform = "PlayStation 4",
                            Price = 49.99m,
                            Title = "Ghost of Tsushima"
                        },
                        new
                        {
                            GameID = 24,
                            Category = "RPG",
                            CoverImageURL = "/images/bloodborne.jpg",
                            Description = "A gothic action RPG with intense combat mechanics.",
                            DownloadSize = 2500000000L,
                            LanguageSupport = "English, French",
                            Platform = "PlayStation 4",
                            Price = 39.99m,
                            Title = "Bloodborne"
                        },
                        new
                        {
                            GameID = 25,
                            Category = "Racing",
                            CoverImageURL = "/images/gran_turismo_sport.jpg",
                            Description = "A racing simulation with lifelike graphics.",
                            DownloadSize = 4000000000L,
                            LanguageSupport = "English, German",
                            Platform = "PlayStation 4",
                            Price = 29.99m,
                            Title = "Gran Turismo Sport"
                        },
                        new
                        {
                            GameID = 26,
                            Category = "Adventure",
                            CoverImageURL = "/images/zelda_breath_wild.jpg",
                            Description = "An open-world adventure in the land of Hyrule.",
                            DownloadSize = 1500000000L,
                            LanguageSupport = "English, French",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            GameID = 27,
                            Category = "Simulation",
                            CoverImageURL = "/images/animal_crossing.jpg",
                            Description = "A life-simulation game where you build your island paradise.",
                            DownloadSize = 5000000000L,
                            LanguageSupport = "English, Spanish",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Title = "Animal Crossing: New Horizons"
                        },
                        new
                        {
                            GameID = 28,
                            Category = "Platformer",
                            CoverImageURL = "/images/super_mario_odyssey.jpg",
                            Description = "A 3D Mario platformer with a globe-trotting adventure.",
                            DownloadSize = 3000000000L,
                            LanguageSupport = "English, Japanese",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            GameID = 29,
                            Category = "Racing",
                            CoverImageURL = "/images/mario_kart8.jpg",
                            Description = "A fun kart-racing game featuring Nintendo characters.",
                            DownloadSize = 5000000000L,
                            LanguageSupport = "English, Italian",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Title = "Mario Kart 8 Deluxe"
                        },
                        new
                        {
                            GameID = 30,
                            Category = "Shooter",
                            CoverImageURL = "/images/splatoon3.jpg",
                            Description = "A colorful third-person shooter where ink is your weapon.",
                            DownloadSize = 2500000000L,
                            LanguageSupport = "English, French",
                            Platform = "Nintendo Switch",
                            Price = 59.99m,
                            Title = "Splatoon 3"
                        });
                });

            modelBuilder.Entity("CVGS.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CVGS.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CVGS.Entities.Preference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<string>("AvailablePlatforms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavouriteGameCategories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavouritePlatforms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguagePreferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("CVGS.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Approved = true,
                            Content = "Black  jack",
                            GameId = 1,
                            Rating = 1,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            Id = 5,
                            Approved = true,
                            Content = "Epic cyberpunky game",
                            GameId = 6,
                            Rating = 3,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            Id = 2,
                            Approved = false,
                            Content = "sui",
                            GameId = 11,
                            Rating = 5,
                            UserId = "042f95a1-3247-4e6a-a375-d2165a8bf16c"
                        },
                        new
                        {
                            Id = 3,
                            Approved = true,
                            Content = "john uncharted",
                            GameId = 21,
                            Rating = 3,
                            UserId = "88193658-5295-478b-9f7e-534f739a06bc"
                        },
                        new
                        {
                            Id = 4,
                            Approved = true,
                            Content = "very open",
                            GameId = 26,
                            Rating = 5,
                            UserId = "bac4f198-0003-438a-a347-2c27bc0e0ffa"
                        });
                });

            modelBuilder.Entity("CVGS.Entities.ShippingAddress", b =>
                {
                    b.Property<int>("ShippingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingAddressId"));

                    b.Property<string>("ShippingAptSuite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingStreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShippingAddressId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("CVGS.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PreferenceId")
                        .HasColumnType("int");

                    b.Property<bool?>("ReceivePromotionalEmails")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CVGS.Entities.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlist");

                    b.HasData(
                        new
                        {
                            WishlistId = 1,
                            GameId = 1,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            WishlistId = 2,
                            GameId = 2,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            WishlistId = 3,
                            GameId = 11,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            WishlistId = 4,
                            GameId = 25,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            WishlistId = 5,
                            GameId = 6,
                            UserId = "05e61254-11dc-44d9-89e7-0e574ce7099a"
                        },
                        new
                        {
                            WishlistId = 6,
                            GameId = 3,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            WishlistId = 7,
                            GameId = 4,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            WishlistId = 8,
                            GameId = 28,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            WishlistId = 9,
                            GameId = 13,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            WishlistId = 10,
                            GameId = 30,
                            UserId = "6c9c58e6-5b8d-42c5-8cf9-1e7c7480f5d2"
                        },
                        new
                        {
                            WishlistId = 11,
                            GameId = 30,
                            UserId = "042f95a1-3247-4e6a-a375-d2165a8bf16c"
                        },
                        new
                        {
                            WishlistId = 12,
                            GameId = 23,
                            UserId = "042f95a1-3247-4e6a-a375-d2165a8bf16c"
                        },
                        new
                        {
                            WishlistId = 13,
                            GameId = 20,
                            UserId = "042f95a1-3247-4e6a-a375-d2165a8bf16c"
                        },
                        new
                        {
                            WishlistId = 14,
                            GameId = 1,
                            UserId = "042f95a1-3247-4e6a-a375-d2165a8bf16c"
                        });
                });

            modelBuilder.Entity("GameWishlist", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("GameID", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("GameWishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserWishlist", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("UserWishlist");
                });

            modelBuilder.Entity("Address", b =>
                {
                    b.HasOne("CVGS.Entities.ShippingAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.HasOne("CVGS.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("Address", "UserId");

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVGS.Entities.Cart", b =>
                {
                    b.HasOne("CVGS.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVGS.Entities.CartItem", b =>
                {
                    b.HasOne("CVGS.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVGS.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CVGS.Entities.Order", b =>
                {
                    b.HasOne("CVGS.Entities.ShippingAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("CVGS.Entities.OrderDetail", b =>
                {
                    b.HasOne("CVGS.Entities.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVGS.Entities.Preference", b =>
                {
                    b.HasOne("CVGS.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CVGS.Entities.Preference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVGS.Entities.Review", b =>
                {
                    b.HasOne("CVGS.Entities.Game", "Game")
                        .WithMany("Review")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVGS.Entities.User", "User")
                        .WithMany("Review")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVGS.Entities.ShippingAddress", b =>
                {
                    b.HasOne("CVGS.Entities.User", "User")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("CVGS.Entities.ShippingAddress", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameWishlist", b =>
                {
                    b.HasOne("CVGS.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVGS.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CVGS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CVGS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVGS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CVGS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserWishlist", b =>
                {
                    b.HasOne("CVGS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVGS.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVGS.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CVGS.Entities.Game", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("CVGS.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CVGS.Entities.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Preferences");

                    b.Navigation("Review");

                    b.Navigation("ShippingAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
